name: Style Checks
on: [pull_request]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install
      id: install
      run : pip install -r tests/lint_requirements.txt

    - name: check
      id: flake8
      run: |
        flake8 --version
        flake8 inheritance_explorer/

  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install
      id: install
      run : pip install -r tests/lint_requirements.txt

    - name: check
      id: black
      run: |
        black --version
        black --check --diff inheritance_explorer/

  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: install
      id: install
      run : pip install -r tests/lint_requirements.txt

    - name: check
      id: isort
      run: |
        isort --version-number
        isort inheritance_explorer --check --diff

